services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nginx-web-php
    container_name: "nginx-web-php"
    volumes:
      - ../src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: "nginx-php"
    volumes:
      - ../src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge