services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: my_database # Optional: Create a default database
      MYSQL_USER: anna
      MYSQL_PASSWORD: anna
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Persist data in a named volume

volumes:
  mysql_data: